export const BUSINESS = {
  name: "Stretched By Angel",
  legalName: "Stretched By Angel",
  url: "https://stretchedbyangel.com",
  logo: "https://019cb84d-8ead-73c3-a40b-714550aaa6fe.mochausercontent.com/stretched-by-angel-transparent.png",
  image: "https://019cb84d-8ead-73c3-a40b-714550aaa6fe.mochausercontent.com/IMG-20260208-WA0012.jpg",
  description:
    "Professional assisted PNF stretching and personal training on the Gold Coast by Angel Elliott.",
  email: "angelfitnessjsyci@icloud.com",
  telephone: "+61434773815",
  phoneDisplay: "0434 773 815",
  whatsapp: "https://wa.me/61434773815",
  instagram: "https://instagram.com/angelfitnessau",
  instagramHandle: "@angelfitnessau",
  priceRange: "$$",
  currency: "AUD",
  address: {
    streetAddress: "Wicked Bodz Fitness Centre, 45 Cavill Ave",
    addressLocality: "Surfers Paradise",
    addressRegion: "QLD",
    postalCode: "4217",
    addressCountry: "AU",
  },
  geo: { latitude: -28.0027, longitude: 153.431 },
  openingHours: {
    dayOfWeek: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    opens: "06:00",
    closes: "20:00",
  },
};

export const AREAS_SERVED = [
  "Surfers Paradise",
  "Broadbeach",
  "Burleigh Heads",
  "Palm Beach",
  "Coolangatta",
  "Southport",
  "Labrador",
  "Main Beach",
  "Mermaid Beach",
  "Miami",
  "Robina",
  "Varsity Lakes",
  "Currumbin",
  "Tugun",
  "Kirra",
  "Bilinga",
  "Runaway Bay",
  "Paradise Point",
  "Coomera",
  "Helensvale",
  "Nerang",
  "Mudgeeraba",
  "Ashmore",
  "Benowa",
  "Carrara",
  "Gold Coast",
  "Upper Coomera",
  "Pimpama",
  "Ormeau",
  "Oxenford",
  "Pacific Pines",
  "Arundel",
];

export const ANGEL = {
  name: "Angel Elliott",
  jobTitle: "Certified Stretch Therapist & Personal Trainer",
  yearsExperience: 10,
  image:
    "https://019cb84d-8ead-73c3-a40b-714550aaa6fe.mochausercontent.com/Picsart_26-03-05_07-10-49-345.jpg",
  knowsAbout: [
    "PNF Stretching",
    "Assisted Stretching",
    "Personal Training",
    "Flexibility Training",
    "Muscle Recovery",
    "Sports Massage",
  ],
};
